# Generated by Django 4.0.3 on 2022-05-31 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_examdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examdetails',
            old_name='Eid',
            new_name='EXID',
        ),
        migrations.RenameField(
            model_name='examdetails',
            old_name='Date',
            new_name='dt',
        ),
    ]
