# Generated by Django 4.0.3 on 2022-05-31 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_eid_examdetails_exid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examdetails',
            old_name='EXID',
            new_name='id',
        ),
    ]
