# Generated by Django 4.0.3 on 2022-07-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_exid_examdetails_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Id', models.CharField(max_length=100)),
                ('RId', models.CharField(max_length=100)),
            ],
        ),
    ]
